require "./lib/cli_project/cli"
require "./lib/cli_project/api"
require "./lib/cli_project/ip_detective"
require "./lib/cli_project/title"

require "pry"
require "httparty"
require "shodanz"
require "ipaddress"
require "dotenv/load"